<a href="https://colab.research.google.com/github/ajaykumar080286/DeepLearning/blob/master/9_backpropagation_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [82]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [83]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=[['cgpa', 'profile_score', 'lpa']])

In [84]:
df.head()

  cgpa profile_score lpa
0    8             8   4
1    7             9   5
2    6            10   6
3    5            12   7

In [85]:
df=pd.DataFrame({
    "cgpa":[8,7,6,5],
    "profile_score":[8,9,10,12],
    "lpa":[4,5,6,7]

})

In [86]:
df.head()

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [87]:
np.ones((4,3))*0.1

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

In [88]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [89]:
np.ones((2,1))*0.1

array([[0.1],
       [0.1]])

In [90]:
np.zeros((1,1))

array([[0.]])

In [91]:
def initialize_parameters(layer_dims):
  np.random.seed(3)
  parameters={}
  L=len(layer_dims)

  for l in range(1,L):
    parameters["W"+str(l)]=np.ones((layer_dims[l-1],layer_dims[l]))*0.1
    parameters["b"+str(l)]=np.zeros((layer_dims[l],1))
    return parameter

In [92]:
parameter=initialize_parameters([2,2,1])

In [93]:
parameter

{'W1': array([[0.12182423, 0.12182423],
        [0.12182423, 0.12182423]]),
 'b1': array([[0.00272803],
        [0.00272803]]),
 'W2': array([[0.135328],
        [0.135328]]),
 'b2': array([[0.142688]])}

In [94]:
parameter["W1"]

array([[0.12182423, 0.12182423],
       [0.12182423, 0.12182423]])

In [95]:
parameter["b1"]

array([[0.00272803],
       [0.00272803]])

In [96]:
parameter["W2"]

array([[0.135328],
       [0.135328]])

In [97]:
len(parameter)

4

In [98]:
def linear_forward(A_prev,W,b):
  Z= np.dot(W.T,A_prev)+b
  return Z

In [99]:
def L_layer_forward(X,parameter):

  A=X
  L = len(parameters) // 2

  for l in range(1,L+1):

    A_prev=A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]

    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)

  return A,A_prev

In [100]:
X=df[["cgpa","profile_score"]].values[0].reshape(2,1)
y=df[["lpa"]].values[0][0]
parameters=initialize_parameters([2,2,1])


y_hat,A1 = L_layer_forward(X, parameter)

In [101]:
y_hat,A1

(array([[0.67098568]]),
 array([[1.95191563],
        [1.95191563]]))

In [102]:
((y-y_hat[0][0])**2).round(2)

np.float64(11.08)

In [103]:
parameters

{'W1': array([[0.12182423, 0.12182423],
        [0.12182423, 0.12182423]]),
 'b1': array([[0.00272803],
        [0.00272803]]),
 'W2': array([[0.135328],
        [0.135328]]),
 'b2': array([[0.142688]])}

In [106]:
y_hat=y_hat[0][0]

In [107]:
update_parameters(parameters,y,y_hat,A1,X)

In [108]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [109]:
parameters

{'W1': array([[0.13831716, 0.13831716],
        [0.13831716, 0.13831716]]),
 'b1': array([[0.00478964],
        [0.00478964]]),
 'W2': array([[0.16131982],
        [0.16131982]]),
 'b2': array([[0.16797785]])}

In [110]:
X=df[["cgpa","profile_score"]].values[1].reshape(2,1)
y=df[["lpa"]].values[1][0]
parameters=initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(X, parameter)
y_hat=y_hat[0][0]
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.14866637, 0.15162329],
        [0.14866637, 0.15162329]]),
 'b1': array([[0.0062681],
        [0.0062681]]),
 'W2': array([[0.17957928],
        [0.17957928]]),
 'b2': array([[0.18781218]])}

In [112]:
X=df[["cgpa","profile_score"]].values[2].reshape(2,1)
y=df[["lpa"]].values[2][0]
parameters=initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(X, parameter)
y_hat=y_hat[0][0]
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.17355784, 0.19310907],
        [0.17370546, 0.19335511]]),
 'b1': array([[0.01041668],
        [0.01044129]]),
 'W2': array([[0.22743497],
        [0.22955928]]),
 'b2': array([[0.2389611]])}

In [113]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.18736502, 0.2262463 ],
        [0.18781545, 0.22721907]]),
 'b1': array([[0.01317812],
        [0.01326328]]),
 'W2': array([[0.25902025],
        [0.26470084]]),
 'b2': array([[0.27536192]])}

In [114]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  9.941032756319485
Epoch -  2 Loss -  3.494166158667027
Epoch -  3 Loss -  1.400390079832254
Epoch -  4 Loss -  1.1925660870618082
Epoch -  5 Loss -  1.2533904154827908

{'W1': array([[0.2757091 , 0.40607281],
        [0.28271141, 0.42215874]]),
 'b1': array([[0.02940107],
        [0.03078632]]),
 'W2': array([[0.43470906],
        [0.48990764]]),
 'b2': array([[0.49250164]])}